ShoppingCart/Presentation/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.Controllers
{
    public class CartController : Controller
    {
        private IProductsService _productsService;
        private ICategoryService _categoriesService;
        private ICartProductService _cartProductService;
        private IWebHostEnvironment _env;
        private readonly ILogger<CartController> _logger;

        public CartController(IProductsService productsService, ICategoryService categoriesService, IWebHostEnvironment env, ICartProductService cartProductService, ILogger<CartController> logger)
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _cartProductService = cartProductService;
            _logger = logger;
            _env = env;
        }

        [Authorize]
        public IActionResult ViewCart()
        {
            //TO DO: Return USER Cart Products 
            string email = HttpContext.User.Identity.Name;
            try
            {
                var list = _cartProductService.GetCartProducts(email);
                return View(list);
            }
            catch (Exception ex)
            {
                _logger.LogError("View cart error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }          
        }

        [Authorize]
        public IActionResult Checkout()
        {
            string email = HttpContext.User.Identity.Name;
            try
            {
                _cartProductService.Checkout(email);
                TempData["CheckoutSuccess"] = "Checkout Successful";
            }
            catch(Exception ex)
            {
                _logger.LogError("Checkout error: "+ex.Message);
                TempData["CheckoutFail"] = "Checkout Failed!";
                return RedirectToAction("Error","Home");
            }
            return RedirectToAction("ViewCart");
        }
    }
}

ShoppingCart/Presentation/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using ShoppingCart.Domain.Models;

namespace Presentation.Controllers
{
    public class ProductsController : Controller
    {
        private IProductsService _productsService;
        private ICategoryService _categoriesService;
        private IWebHostEnvironment _env;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(ILogger<ProductsController> logger,IProductsService productsService, ICategoryService categoriesService,IWebHostEnvironment env)
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _logger = logger;
            _env = env;
        }

        public async Task<IActionResult> Index(string searchString, int pagenumber = 1)
        {
            ViewData["CurrentFilter"] = searchString;

            try
            {
                var list = _productsService.GetProducts();
                var catList = _categoriesService.GetCategories();
                ViewBag.Categories = catList;

                if (!String.IsNullOrEmpty(searchString))
                {
                    list = _productsService.GetProductsByCateg(searchString);
                }
                return View(await PaginatedList<ProductViewModel>.CreateAsync(list, pagenumber, 10));
            } catch (Exception ex)
            {
                _logger.LogError("Display error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }

            
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            try
            {
                var catList = _categoriesService.GetCategories();
                ViewBag.Categories = catList;
            }
            catch(Exception ex)
            {
                _logger.LogError("Add error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }
            
            return View();
        }

        public IActionResult Details(Guid id)
        {
            try
            {
                var myProduct = _productsService.GetProduct(id);
                return View(myProduct);
            }
            catch(Exception ex)
            {
                _logger.LogError("View details error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }
            
        }

        public IActionResult ViewOrders()
        {
            string email = HttpContext.User.Identity.Name;
            var orderList = _productsService.GetOrderDetailProducts(email);
            foreach(var i in orderList)
            {
                Console.WriteLine();
            }
            return View(orderList);
        }

        public IActionResult SingleMealPlan()
        {
            return View();

        }

        public IActionResult WeeklyMealPlan()
        {
            return View();

        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Add(ProductViewModel data, IFormFile file)
        {
            try
            {
                if (file != null)
                {
                    if (file.Length > 0)
                    {
                        string newFileName = Guid.NewGuid() + System.IO.Path.GetExtension(file.FileName);
                        string absolutePath = _env.WebRootPath + @"\Images\";

                        using (var stream = System.IO.File.Create(absolutePath + newFileName))
                        {
                            file.CopyTo(stream);
                        }

                        data.ImageUrl = @"\Images\" + newFileName;

                    }
                }
                _productsService.AddProduct(data);
                ViewData["feedback"] = "Product was added successfully";
                ModelState.Clear();
            }
            catch (Exception ex)
            {
                //log errors
                ViewData["warning"] = "Product was not added! Check your details";
                _logger.LogError("Adding Product error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }

            var catList = _categoriesService.GetCategories();
            ViewBag.Categories = catList;

            return View();

        }
        [Authorize]
        public IActionResult AddToCart(Guid id,int qty)
        {
            string email = HttpContext.User.Identity.Name;
            try
            {
                if(!_productsService.CheckStock(id,qty))
                {
                    TempData["AddToCartFail"] = "Invalid Quantity";
                    return RedirectToAction("Index");
                }
                _productsService.AddToCart(id, email,qty);
                TempData["AddToCartSuccess"] = "Successfully Added To Cart";
            } catch (Exception ex)
            {
                TempData["AddToCartFail"] = "Product was not added! Check your details";
                _logger.LogError("Add to cart error: " + ex.Message);
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Hide(Guid id)
        {
            _productsService.Hide(id);
            TempData["Hide"] = "Product hidden";
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Show(Guid id)
        {
            _productsService.Show(id);
            TempData["Show"] = "Product available";
            return RedirectToAction("Index");
        }


    }
}

ShoppingCart/Presentation/Views/Shared/_Feedback.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@if (@TempData["AddToCartSuccess"] != null)
{
    <div class="alert alert-primary">@TempData["AddToCartSuccess"]</div>
}
else if (@TempData["AddToCartFail"] != null)
{
    <div class="alert alert-warning" role="alert">@TempData["AddToCartFail"]</div>
}
else if (@TempData["CheckoutSuccess"] != null)
{
    <div class="alert alert-primary">@TempData["CheckoutSuccess"]</div>
}
else if (@TempData["CheckoutFail"] != null)
{
    <div class="alert alert-warning" role="alert">@TempData["CheckoutFail"]</div>
}
else if (@TempData["Show"] != null)
{
    <div class="alert alert-primary">@TempData["Show"]</div>
}
else if (@TempData["Hide"] != null)
{
    <div class="alert alert-primary">@TempData["Hide"]</div>
}

ShoppingCart/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping Cart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LETSCOOKIT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Nutritionist">Contact Nutritionist</a>
                        </li>
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Add">Add Products</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Meal Plans</a>
                        </li>
                        @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">Shopping Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="ViewOrders">My Orders</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @if (@ViewData["feedback"] != null)
            {
                <div class="alert alert-primary">@ViewData["feedback"]</div>
            }
            else if (ViewData["warning"] != null)
            {
                <div class="alert alert-warning" role="alert">@ViewData["warning"]</div>
            }
            <partial name="_FeedBack" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LETSCOOKIT LTD - <a asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ShoppingCart/Presentation/Views/Shared/_ViewProducts.cshtml
@using ShoppingCart.Domain.Models
@model PaginatedList<ShoppingCart.Application.ViewModels.ProductViewModel>



<div class="row">
    @foreach (var product in Model)
    {
        if (product.Availability == "Available" || ViewContext.HttpContext.User.IsInRole("Admin"))
        {
        <div class="col-4 mb-5 d-flex align-items-stretch">
            <div class="card" style="width: 18rem;">
                <img src="@product.ImageUrl" class="card-img-top" alt="@product.Name">
                <div class="card-body">
                    <h5 class="card-title">@product.Name</h5>
                    <p class="card-text">Available quantity: @product.Stock</p>
                    <p class="card-text">€@product.Price</p>
                    <input type="number" id="@product.Id" class="form-control" value="1"/>
                    <a href="/Products/Details?id=@product.Id" class="btn btn-primary">View More Information</a>
                    <!--<a asp-controller="Products" asp-action="AddToCart" asp-route-id="@product.Id" onclick="this.href+=document.getElementById('qta_field').value" class="btn btn-primary">Add to Cart</a>-->
                    <a href='' onclick="this.href='Products/AddToCart?id=@product.Id&qty='+document.getElementById('@product.Id').value" class="btn btn-primary">Add To Cart</a>
                    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                    {
                        if (product.Availability == "Available")
                        {
                            <a asp-controller="Products" asp-action="Hide" asp-route-id="@product.Id" onclick="return window.confirm('Are you sure?')" class="btn btn-secondary">Hide</a>
                        }
                        else
                        {
                            <a asp-controller="Products" asp-action="Show" asp-route-id="@product.Id" onclick="return window.confirm('Are you sure?')" class="btn btn-secondary">Show</a>
                        }
                    }
                </div>
            </div>
        </div>
        }
    }
</div>


@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>